version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: 'development'
      BUNDLE_PATH: '/gems'
      RAILS_LOG_TO_STDOUT: 'true'
    volumes:
      - .:/myapp
      - gems:/gems
    ports:
      - '3000:3000'
    command: bundle check || bundle install

volumes:
  gems:
